fix(SWFFT/SWFFT_poisson)
AMReX-Codes/amrex-tutorials pull request #133
Opened 2024-08-27 16:57 UTC by YL-codehub

- rank-mapping didn't have to be modified from fortran to C order, already carried out.
- already done so in SWFFT/Simple.

2024-08-28 21:06 UTC, WeiqunZhang requested changes

2024-08-29 13:12 UTC, YL-codehub commented on ExampleCodes/SWFFT/SWFFT_poisson/swfft_solver.cpp
> +    Vector<int> rank_mapping = rhs.DistributionMap().ProcessorMap(); // copy the ranks' ordering
I see! it should have been fixed now, thanks!

2024-08-29 16:24 UTC, WeiqunZhang commented on ExampleCodes/SWFFT/SWFFT_poisson/swfft_solver.cpp
> +
```suggestion
```

2024-09-02 18:35 UTC, WeiqunZhang approved these changes

2024-09-02 18:35 UTC, merged